micronaut:
  application:
    name: JWTLogin
  firebase:
    admin-sdk-service-account-file: home/student/Licenta/DataBase/firebase.json

---
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET_1:M3iYQYrGyOKxGFgQf7SuDbWA5hzz7j}"'
---
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET_2:xIJkp3jr72sEFO3AUonCov7PNyGAfJ}"'

---
micronaut:
  security:
    token:
      jwt:
        generator:
          access-token:
            expiration: 300