micronaut:
  server:
    port: 8089

---
micronaut:
  server:
    cors:
      enabled: true

      configurations:
        ui:
          allowed-origins:
            - http://localhost:4200

---
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET_1:M3iYQYrGyOKxGFgQf7SuDbWA5hzz7j}"'

---
micronaut:
  security:
    endpoints:
      enabled: true
      get-allowed: true

---
mongodb:
  uri: "mongodb+srv://cosminirimiaaursulesei:t9pam*JtJYk5M@cluster0.zfa9zls.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  database: "test"