application:
  name: JWTLogin
firebase:
  admin-sdk-service-account-file: home/student/Licenta/DataBase/firebase.json

micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET_1:M3iYQYrGyOKxGFgQf7SuDbWA5hzz7j}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET_2:xIJkp3jr72sEFO3AUonCov7PNyGAfJ}"'

---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: "'${JWT_GENERATOR_SIGNATURE_SECRET_1:M3iYQYrGyOKxGFgQf7SuDbWA5hzz7j}'"

---
micronaut:
  security:
    token:
      generator:
        access-token:
          expiration: 60

---
micronaut:
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:4200

---
micronaut:
  security:
    endpoints:
      enabled: true
      get-allowed: true


---
micronaut:
  server:
    port: 8081

---
micronaut:
  http:
    services:
      afisareCursuri:
        urls:
          - "http://localhost:8082"
          -

---
micronaut:
  security:
    token:
      jwt:
        signatures:
          jwks:
            awscognito:
              url: 'https://cognito-idp.eu-west-1.amazonaws.com/eu-west-XXXX/.well-known/jwks.json'